# Generated by Django 3.1.5 on 2021-01-20 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, unique=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fake_name', models.TextField(default='John Doe', max_length=50)),
                ('fake_avatar', models.TextField(blank=True, max_length=500)),
                ('fake_location', models.TextField(blank=True, max_length=500)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2021, 1, 27, 16, 34, 26, 460571, tzinfo=utc))),
                ('last_days', models.IntegerField(default=7)),
                ('like_count', models.IntegerField(default=0.0)),
                ('fail_count', models.IntegerField(default=0.0)),
                ('fail_index', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
