# Generated by Django 3.1.5 on 2021-01-07 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500, unique=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2021, 2, 7, 22, 8, 7, 326451, tzinfo=utc))),
                ('like_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('like_index', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
