# Generated by Django 3.1.4 on 2020-12-28 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 22, 37, 58, 48643)),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
