# Generated by Django 3.1.5 on 2021-01-07 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fake_name',
            field=models.TextField(default='John Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 22, 34, 40, 203557, tzinfo=utc)),
        ),
    ]
