# Generated by Django 3.1.4 on 2020-12-28 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201228_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 23, 0, 42, 452045)),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
