# Generated by Django 3.1.5 on 2021-01-07 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210107_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fake_avatar',
            field=models.TextField(default='https://i.pravatar.cc/150', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 22, 55, 15, 524159, tzinfo=utc)),
        ),
    ]
