# Generated by Django 3.1.5 on 2021-01-20 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210120_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 22, 57, 50, 317816, tzinfo=utc)),
        ),
    ]
