# Generated by Django 3.1.5 on 2021-01-21 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210120_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 0, 44, 37, 456204, tzinfo=utc)),
        ),
    ]
