# Generated by Django 3.1.5 on 2021-01-07 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210107_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 22, 57, 12, 582353, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fake_avatar',
            field=models.TextField(max_length=500),
        ),
    ]
