# Generated by Django 3.1.5 on 2021-01-07 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210107_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fake_location',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 23, 15, 17, 366576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='fake_avatar',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
