# Generated by Django 3.1.5 on 2021-01-09 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210108_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 12, 48, 9, 895427, tzinfo=utc)),
        ),
    ]
