# Generated by Django 3.1.4 on 2020-12-28 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201228_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 23, 59, 37, 728336)),
        ),
    ]
