# Generated by Django 3.1.5 on 2021-01-05 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20201229_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 12, 58, 3, 114259, tzinfo=utc)),
        ),
    ]
